/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package meetingschedulingsystemtest;

/**
 *
 * @author hozaifa
 */
public class AddPersonMenu extends javax.swing.JFrame {

    /**
     * Creates new form AddPersonMenu
     */
    public AddPersonMenu() {
        initComponents();
    }

    public String getFirstName(){
        return firstNamePersonMenuTF.getText();
    }
    public String getLastName(){
        return lastNamePersonMenuTF.getText();
    }
    public String getPhoneNumber(){
        return phoneNumberPersonMenuTF.getText();
    }
    MeetingScheduleSystemMainMenu MSSMM = new MeetingScheduleSystemMainMenu();
    Meeting meeting = new Meeting();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addPersonPanel = new javax.swing.JPanel();
        firstNamePersonLabel = new javax.swing.JLabel();
        lastNamePersonLabel = new javax.swing.JLabel();
        phoneNumberPersonLabel = new javax.swing.JLabel();
        firstNamePersonMenuTF = new javax.swing.JTextField();
        lastNamePersonMenuTF = new javax.swing.JTextField();
        phoneNumberPersonMenuTF = new javax.swing.JTextField();
        submitPersonMenuPanel = new javax.swing.JPanel();
        submitPersonMenuButton = new javax.swing.JButton();
        addPersonPanel1 = new javax.swing.JPanel();
        firstNamePersonLabel1 = new javax.swing.JLabel();
        lastNamePersonLabel1 = new javax.swing.JLabel();
        phoneNumberPersonLabel1 = new javax.swing.JLabel();
        firstNamePersonMenuTF1 = new javax.swing.JTextField();
        lastNamePersonMenuTF1 = new javax.swing.JTextField();
        phoneNumberPersonMenuTF1 = new javax.swing.JTextField();
        submitPersonMenuPanel1 = new javax.swing.JPanel();
        submitPersonMenuButton1 = new javax.swing.JButton();
        phoneNumberPersonMenuTF2 = new javax.swing.JTextField();
        phoneNumberPersonLabel2 = new javax.swing.JLabel();

        addPersonPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add Person", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Abyssinica SIL", 0, 14))); // NOI18N

        firstNamePersonLabel.setText("First Name:");

        lastNamePersonLabel.setText("Last Name:");

        phoneNumberPersonLabel.setText("Phone Number: ");

        submitPersonMenuPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Submit", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Abyssinica SIL", 0, 14))); // NOI18N

        submitPersonMenuButton.setText("Submit");
        submitPersonMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitPersonMenuButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout submitPersonMenuPanelLayout = new javax.swing.GroupLayout(submitPersonMenuPanel);
        submitPersonMenuPanel.setLayout(submitPersonMenuPanelLayout);
        submitPersonMenuPanelLayout.setHorizontalGroup(
            submitPersonMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, submitPersonMenuPanelLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(submitPersonMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        submitPersonMenuPanelLayout.setVerticalGroup(
            submitPersonMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(submitPersonMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(submitPersonMenuButton)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout addPersonPanelLayout = new javax.swing.GroupLayout(addPersonPanel);
        addPersonPanel.setLayout(addPersonPanelLayout);
        addPersonPanelLayout.setHorizontalGroup(
            addPersonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPersonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addPersonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(addPersonPanelLayout.createSequentialGroup()
                        .addComponent(lastNamePersonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lastNamePersonMenuTF, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addPersonPanelLayout.createSequentialGroup()
                        .addComponent(firstNamePersonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(firstNamePersonMenuTF, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addPersonPanelLayout.createSequentialGroup()
                        .addComponent(phoneNumberPersonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(phoneNumberPersonMenuTF, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, Short.MAX_VALUE)
                .addComponent(submitPersonMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        addPersonPanelLayout.setVerticalGroup(
            addPersonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPersonPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(addPersonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPersonPanelLayout.createSequentialGroup()
                        .addGroup(addPersonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firstNamePersonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstNamePersonMenuTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(addPersonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastNamePersonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lastNamePersonMenuTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(submitPersonMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(addPersonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneNumberPersonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneNumberPersonMenuTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        addPersonPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add Person to Meeting", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Abyssinica SIL", 0, 14))); // NOI18N

        firstNamePersonLabel1.setText("First Name:");

        lastNamePersonLabel1.setText("Last Name:");

        phoneNumberPersonLabel1.setText("Phone Number: ");

        submitPersonMenuPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Submit", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Abyssinica SIL", 0, 14))); // NOI18N

        submitPersonMenuButton1.setText("Submit");
        submitPersonMenuButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitPersonMenuButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout submitPersonMenuPanel1Layout = new javax.swing.GroupLayout(submitPersonMenuPanel1);
        submitPersonMenuPanel1.setLayout(submitPersonMenuPanel1Layout);
        submitPersonMenuPanel1Layout.setHorizontalGroup(
            submitPersonMenuPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, submitPersonMenuPanel1Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(submitPersonMenuButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        submitPersonMenuPanel1Layout.setVerticalGroup(
            submitPersonMenuPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(submitPersonMenuPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(submitPersonMenuButton1)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        phoneNumberPersonLabel2.setText("Meeting Name: ");

        javax.swing.GroupLayout addPersonPanel1Layout = new javax.swing.GroupLayout(addPersonPanel1);
        addPersonPanel1.setLayout(addPersonPanel1Layout);
        addPersonPanel1Layout.setHorizontalGroup(
            addPersonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPersonPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addPersonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(addPersonPanel1Layout.createSequentialGroup()
                        .addComponent(lastNamePersonLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lastNamePersonMenuTF1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addPersonPanel1Layout.createSequentialGroup()
                        .addComponent(firstNamePersonLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(firstNamePersonMenuTF1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addPersonPanel1Layout.createSequentialGroup()
                        .addComponent(phoneNumberPersonLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(phoneNumberPersonMenuTF1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(addPersonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPersonPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(phoneNumberPersonLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(phoneNumberPersonMenuTF2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPersonPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submitPersonMenuPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        addPersonPanel1Layout.setVerticalGroup(
            addPersonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPersonPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(addPersonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNamePersonLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstNamePersonMenuTF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneNumberPersonLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneNumberPersonMenuTF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(addPersonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNamePersonLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNamePersonMenuTF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(addPersonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPersonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(phoneNumberPersonLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(phoneNumberPersonMenuTF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(submitPersonMenuPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addPersonPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addPersonPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addPersonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addPersonPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitPersonMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitPersonMenuButtonActionPerformed
        System.out.printf("First Name: %s%n",getFirstName());
        System.out.printf("Last Name: %s%n", getLastName());
        System.out.printf("Phone Number: %s%n" ,getPhoneNumber());
        Person person = new Person(getFirstName(), getLastName(), getPhoneNumber());
        MSSMM.personArray.add(person);
        meeting.addPerson(person);
        System.out.println(MSSMM.personArray.size());
        dispose();
    }//GEN-LAST:event_submitPersonMenuButtonActionPerformed

    private void submitPersonMenuButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitPersonMenuButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_submitPersonMenuButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddPersonMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddPersonMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddPersonMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddPersonMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddPersonMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addPersonPanel;
    private javax.swing.JPanel addPersonPanel1;
    private javax.swing.JLabel firstNamePersonLabel;
    private javax.swing.JLabel firstNamePersonLabel1;
    private javax.swing.JTextField firstNamePersonMenuTF;
    private javax.swing.JTextField firstNamePersonMenuTF1;
    private javax.swing.JLabel lastNamePersonLabel;
    private javax.swing.JLabel lastNamePersonLabel1;
    private javax.swing.JTextField lastNamePersonMenuTF;
    private javax.swing.JTextField lastNamePersonMenuTF1;
    private javax.swing.JLabel phoneNumberPersonLabel;
    private javax.swing.JLabel phoneNumberPersonLabel1;
    private javax.swing.JLabel phoneNumberPersonLabel2;
    private javax.swing.JTextField phoneNumberPersonMenuTF;
    private javax.swing.JTextField phoneNumberPersonMenuTF1;
    private javax.swing.JTextField phoneNumberPersonMenuTF2;
    private javax.swing.JButton submitPersonMenuButton;
    private javax.swing.JButton submitPersonMenuButton1;
    private javax.swing.JPanel submitPersonMenuPanel;
    private javax.swing.JPanel submitPersonMenuPanel1;
    // End of variables declaration//GEN-END:variables
}
