/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package meetingschedulingsystemtest;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

/**
 *
 * @author hozaifa
 */
public class DeletePerson extends javax.swing.JFrame {

    /**
     * Creates new form DeletePerson
     */
    public DeletePerson() {
        initComponents();
        initPersonList();
    }
    
    // initializes person list with all people not associated with a meeting
    private void initPersonList() {
        String firstName, lastName, fullName;
        DefaultListModel data = new DefaultListModel();
        jList1.setModel(data);
        MeetingScheduleSystemMainMenu MSSMM = new MeetingScheduleSystemMainMenu();
        if(!MSSMM.personArray.isEmpty()){
            for(int i=0; i<MSSMM.personArray.size();i++){
                firstName = MSSMM.personArray.get(i).getFirstName();
                lastName = MSSMM.personArray.get(i).getLastName();
                fullName = firstName + " " + lastName;
                data.add(i,fullName);
            }
            jList1.setModel(data);    
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DeletePersonPanel = new javax.swing.JPanel();
        submitPanel = new javax.swing.JPanel();
        deletePersonSubmit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        DeletePersonPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Delete Person", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Abyssinica SIL", 0, 14))); // NOI18N

        submitPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Submit", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Abyssinica SIL", 0, 14))); // NOI18N

        deletePersonSubmit.setText("Submit");
        deletePersonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePersonSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout submitPanelLayout = new javax.swing.GroupLayout(submitPanel);
        submitPanel.setLayout(submitPanelLayout);
        submitPanelLayout.setHorizontalGroup(
            submitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, submitPanelLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(deletePersonSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        submitPanelLayout.setVerticalGroup(
            submitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(submitPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(deletePersonSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jList1.setBorder(javax.swing.BorderFactory.createTitledBorder("Delete Person"));
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            MeetingScheduleSystemMainMenu MSSMM = new MeetingScheduleSystemMainMenu();
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }

        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout DeletePersonPanelLayout = new javax.swing.GroupLayout(DeletePersonPanel);
        DeletePersonPanel.setLayout(DeletePersonPanelLayout);
        DeletePersonPanelLayout.setHorizontalGroup(
            DeletePersonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeletePersonPanelLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(submitPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        DeletePersonPanelLayout.setVerticalGroup(
            DeletePersonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeletePersonPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(DeletePersonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DeletePersonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DeletePersonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deletePersonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePersonSubmitActionPerformed
        MeetingScheduleSystemMainMenu MSSMM = new MeetingScheduleSystemMainMenu();
        DeletePerson deletePerson = new DeletePerson();
        String fullName = jList1.getSelectedValue();
        if(fullName ==null){
            dispose();
            JOptionPane.showMessageDialog(null, "Please select a person!", "Invalid Input", JOptionPane.ERROR_MESSAGE);
            deletePerson.setVisible(true);
        }
        else{
            //obtains full name then splits it into first and last name
            String[] Name = fullName.split(" ", 2);
            String firstName = Name[0];
            String lastName = Name[1];
            System.out.println(firstName + " " + lastName);

            //removes selected person
            for(int i=0;i<MSSMM.personArray.size();i++){
                if(MSSMM.personArray.get(i).getFirstName().equals(firstName) && MSSMM.personArray.get(i).getLastName().equals(lastName)){
                    MSSMM.personArray.remove(i);
                    System.out.printf("%nPerson  %s has been deleted!", fullName);
                }
            }
            System.out.println();
            System.out.printf("Array Size: %d%n", MSSMM.meetingArray.size());
            dispose();
        }
    }//GEN-LAST:event_deletePersonSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeletePerson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeletePerson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeletePerson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeletePerson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeletePerson().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DeletePersonPanel;
    private javax.swing.JButton deletePersonSubmit;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel submitPanel;
    // End of variables declaration//GEN-END:variables
}
