/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package meetingschedulingsystemtest;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author hozaifa
 */
public class DeletePersonFromMeetingMenu extends javax.swing.JFrame {

    /**
     * Creates new form DeletePersonFromMeeting
     */
    public DeletePersonFromMeetingMenu() {
        initComponents();
        initPersonList();
        initMeetingList();
    }
    
    // initalizes the person JList with all attendees 
    private void initPersonList() {
        String firstName, lastName, phoneNumber, fullName;
        DefaultListModel data = new DefaultListModel();
        attendeeRemovedList.setModel(data);
        MeetingScheduleSystemMainMenu MSSMM = new MeetingScheduleSystemMainMenu();
        if(!MSSMM.meetingArray.isEmpty()){
            for(int j=0;j<MSSMM.meetingArray.size();j++){
                for(int i=0; i<MSSMM.meetingArray.get(j).getPersonArray().size();i++){
                    firstName = MSSMM.meetingArray.get(j).getPersonArray().get(i).getFirstName();
                    lastName = MSSMM.meetingArray.get(j).getPersonArray().get(i).getLastName();
                    phoneNumber = MSSMM.meetingArray.get(j).getPersonArray().get(i).getPhoneNumber();
                    fullName = firstName + " " + lastName + " " + phoneNumber;
                    data.add(i,fullName);
                }
            }
            attendeeRemovedList.setModel(data);    
        }   
    }
    
    // initializes the meetings JList with all meetings
     private void initMeetingList() {
        DefaultListModel data = new DefaultListModel();
        meetingList.setModel(data);
        MeetingScheduleSystemMainMenu MSSMM = new MeetingScheduleSystemMainMenu();
        for(int i=0; i<MSSMM.meetingArray.size();i++){
            data.add(i,MSSMM.meetingArray.get(i).getMeetingName());
        }
        meetingList.setModel(data); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        attendeeRemovedList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        meetingList = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        deletePersonToMeetingSubmit = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Delete Person From A Meeting", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Abyssinica SIL", 0, 14))); // NOI18N

        attendeeRemovedList.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Select Attendee", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Abyssinica SIL", 0, 14))); // NOI18N
        attendeeRemovedList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        attendeeRemovedList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(attendeeRemovedList);

        meetingList.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Select Meeting", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Abyssinica SIL", 0, 14))); // NOI18N
        meetingList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        meetingList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jScrollPane2.setViewportView(meetingList);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Submit", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Abyssinica SIL", 0, 14))); // NOI18N

        deletePersonToMeetingSubmit.setText("Submit");
        deletePersonToMeetingSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePersonToMeetingSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(deletePersonToMeetingSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(deletePersonToMeetingSubmit, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deletePersonToMeetingSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePersonToMeetingSubmitActionPerformed
        MeetingScheduleSystemMainMenu MSSMM = new MeetingScheduleSystemMainMenu();
        int selectedPerson = attendeeRemovedList.getSelectedIndex();
        int selectedMeeting = meetingList.getSelectedIndex();
        DeletePersonFromMeetingMenu deletPersonFromMeetingMenu = new DeletePersonFromMeetingMenu();
        
        //validates incase the user clicks submit without proper selection of a person and meeting
        if((selectedPerson == -1) || (selectedMeeting == -1)){
            dispose();
            JOptionPane.showMessageDialog(null, "Please select a person and a meeting!", "Invalid Input", JOptionPane.ERROR_MESSAGE);
            deletPersonFromMeetingMenu.setVisible(true);
        }
        else{
            // removes the selected person from the selected meeting
            for(int i=0;i<MSSMM.meetingArray.get(selectedMeeting).getPersonArraySize(); i++){
                System.out.printf("Person: %s%n" ,attendeeRemovedList.getModel().getElementAt(i));
                String fullName = attendeeRemovedList.getModel().getElementAt(selectedPerson);
                String fName = MSSMM.meetingArray.get(selectedMeeting).getPersonArray().get(i).getFirstName();
                String lName = MSSMM.meetingArray.get(selectedMeeting).getPersonArray().get(i).getLastName();
                String pNumber = MSSMM.meetingArray.get(selectedMeeting).getPersonArray().get(i).getPhoneNumber();
                String entireName = fName + " " + lName + " " + pNumber;
                System.out.printf("Entire Name: %s%n", entireName);
                if(entireName.equals(fullName)){
                    //System.out.printf("Person %s is the same as Person %s", MSSMM.meetingArray.get(selectedMeeting).getPersonArray().get(i), person);
                    MSSMM.meetingArray.get(selectedMeeting).removePersonAt(i);
                }
                else{
                    dispose();
                    JOptionPane.showMessageDialog(null, "That Attendee does not Attend that Meeting!", "alert", JOptionPane.ERROR_MESSAGE);
                    deletPersonFromMeetingMenu.setVisible(true);
                }
            }

    //        }
            dispose();
        }
    }//GEN-LAST:event_deletePersonToMeetingSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeletePersonFromMeetingMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeletePersonFromMeetingMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeletePersonFromMeetingMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeletePersonFromMeetingMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeletePersonFromMeetingMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> attendeeRemovedList;
    private javax.swing.JButton deletePersonToMeetingSubmit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> meetingList;
    // End of variables declaration//GEN-END:variables
}
