/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package meetingschedulingsystemtest;

import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SpringLayout;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;


/**
 *
 * @author hozaifa
 */
public class MeetingScheduleSystemMainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MeetingScheduleSystemMainMenu
     */
        static ArrayList<Person> personArray = new ArrayList<Person>();
        static ArrayList<Room> roomArray = new ArrayList<Room>();
        static ArrayList<Meeting> meetingArray = new ArrayList<Meeting>();
        
    public MeetingScheduleSystemMainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        applicationPanel = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        appTitle = new javax.swing.JLabel();
        mainMenuButtons = new javax.swing.JPanel();
        createMeeting = new javax.swing.JButton();
        deleteMeeting = new javax.swing.JButton();
        addPerson = new javax.swing.JButton();
        addRoom = new javax.swing.JButton();
        deleteRoom = new javax.swing.JButton();
        deletePerson = new javax.swing.JButton();
        displayMeeting = new javax.swing.JButton();
        displayRoom = new javax.swing.JButton();
        displayPerson = new javax.swing.JButton();

        javax.swing.GroupLayout applicationPanelLayout = new javax.swing.GroupLayout(applicationPanel);
        applicationPanel.setLayout(applicationPanelLayout);
        applicationPanelLayout.setHorizontalGroup(
            applicationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 231, Short.MAX_VALUE)
        );
        applicationPanelLayout.setVerticalGroup(
            applicationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        appTitle.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        appTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        appTitle.setText("Meeting Scheduling System");
        appTitle.setToolTipText("Meeting Scheduling System");
        appTitle.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        appTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        createMeeting.setText("Create Meeting");
        createMeeting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createMeetingActionPerformed(evt);
            }
        });

        deleteMeeting.setText("Delete Meeting");
        deleteMeeting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMeetingActionPerformed(evt);
            }
        });

        addPerson.setText("Add Person");
        addPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPersonActionPerformed(evt);
            }
        });

        addRoom.setText("Add Room");
        addRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRoomActionPerformed(evt);
            }
        });

        deleteRoom.setText("Delete Room");
        deleteRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteRoomActionPerformed(evt);
            }
        });

        deletePerson.setText("Delete Person");
        deletePerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePersonActionPerformed(evt);
            }
        });

        displayMeeting.setText("Display Meeting");
        displayMeeting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayMeetingActionPerformed(evt);
            }
        });

        displayRoom.setText("Display Room");
        displayRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayRoomActionPerformed(evt);
            }
        });

        displayPerson.setText("Display Person");
        displayPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayPersonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainMenuButtonsLayout = new javax.swing.GroupLayout(mainMenuButtons);
        mainMenuButtons.setLayout(mainMenuButtonsLayout);
        mainMenuButtonsLayout.setHorizontalGroup(
            mainMenuButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainMenuButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(createMeeting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteMeeting, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(displayMeeting, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mainMenuButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(displayRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mainMenuButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deletePerson, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(displayPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        mainMenuButtonsLayout.setVerticalGroup(
            mainMenuButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainMenuButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainMenuButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(createMeeting, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(addPerson, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainMenuButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteMeeting, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deletePerson, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainMenuButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(displayMeeting, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(displayRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(displayPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(appTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(mainMenuButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(appTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(mainMenuButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createMeetingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createMeetingActionPerformed
        
        CreateMeetingMenu createMeetingMenu = new CreateMeetingMenu();
        createMeetingMenu.setVisible(true);
        String meetingName = createMeetingMenu.getMeetingNameTF();
        System.out.println(meetingName);

        
    
    }//GEN-LAST:event_createMeetingActionPerformed

    private void addRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRoomActionPerformed
        AddRoomMenu addRoomMenu = new AddRoomMenu();
        addRoomMenu.setVisible(true);
    }//GEN-LAST:event_addRoomActionPerformed

    private void addPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPersonActionPerformed
        AddPersonMenu addPersonMenu = new AddPersonMenu();
        addPersonMenu.setVisible(true);
    }//GEN-LAST:event_addPersonActionPerformed

    private void deleteMeetingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMeetingActionPerformed
        DeleteMeeting deleteMeetingMenu = new DeleteMeeting();
        deleteMeetingMenu.setVisible(true);
    }//GEN-LAST:event_deleteMeetingActionPerformed

    private void deleteRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteRoomActionPerformed
        DeleteRoom deleteRoomMenu = new DeleteRoom();
        deleteRoomMenu.setVisible(true);
    }//GEN-LAST:event_deleteRoomActionPerformed

    private void deletePersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePersonActionPerformed
        DeletePerson deletePersonMenu = new DeletePerson();
        deletePersonMenu.setVisible(true);
    }//GEN-LAST:event_deletePersonActionPerformed

    private void displayMeetingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayMeetingActionPerformed
        DisplayMeeting displayMeetingMenu = new DisplayMeeting();
        displayMeetingMenu.setVisible(true);
    }//GEN-LAST:event_displayMeetingActionPerformed

    private void displayRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayRoomActionPerformed
        DisplayRoom displayroomMenu = new DisplayRoom();
        displayroomMenu.setVisible(true);
    }//GEN-LAST:event_displayRoomActionPerformed

    private void displayPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayPersonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_displayPersonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MeetingScheduleSystemMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MeetingScheduleSystemMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MeetingScheduleSystemMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MeetingScheduleSystemMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MeetingScheduleSystemMainMenu().setVisible(true);
               
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPerson;
    private javax.swing.JButton addRoom;
    private javax.swing.JLabel appTitle;
    private javax.swing.JPanel applicationPanel;
    private javax.swing.JButton createMeeting;
    private javax.swing.JButton deleteMeeting;
    private javax.swing.JButton deletePerson;
    private javax.swing.JButton deleteRoom;
    private javax.swing.JButton displayMeeting;
    private javax.swing.JButton displayPerson;
    private javax.swing.JButton displayRoom;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel mainMenuButtons;
    // End of variables declaration//GEN-END:variables
}


